Repository nestrilabs/nestri, pull requests merged in 2024-06, with the labels that each got.

#80 🐛 fix(server): Replace netris with nestri in supervisord.conf
  .scripts/supervisord.conf
Labels: size/xs, usr/wanjohi

#81 🐛 fix: Delete `.scripts/supervisord.d` directory
  .scripts/supervisord.conf
  .scripts/supervisord.d/game.ini
Labels: type/fix, size/s, usr/wanjohi

#82 🐛 fix(server): Fix startup aswell change supervisord's username to use nestri
  .scripts/startup.sh
  .scripts/supervisord.conf
Labels: type/fix, scope/back-end

#87 🐛 fix(autolabeller): Use `GITHUB_TOKEN` for autolabelling
  .github/workflows/autolabeller.yml
Labels: type/fix, scope/git, size/xs, usr/wanjohi

#88 🐛 fix(autolabeller): Use GITHUB_TOKEN for adding labels too
  .github/workflows/autolabeller.yml
Labels: type/fix, mergeable/false, scope/git, size/xs, usr/wanjohi

#89 🐛 fix(labeler): Use remote config
  .github/workflows/autolabeler.yml
Labels: type/fix, mergeable/false, scope/git, size/xs, usr/wanjohi

#83 🐛 fix(base): Use meson for gpu-screen-recorder
  base.Dockerfile
Labels: type/fix
