Repository nestrilabs/nestri, pull requests merged in 2024-05, with the labels that each got.

#38 ✨ feat(input): Migrate to moq for input transmission
  .github/workflows/warp-input.yml
  bin/input/.gitignore
  bin/input/Cargo.lock
  bin/input/Cargo.toml
  bin/input/go.mod
  bin/input/main.go
  bin/input/src/cli.rs
  bin/input/src/input.rs
  bin/input/src/main.rs
  warp-input.Dockerfile
Labels: type/feat, scope/git, size/xxl, usr/wanjohi

#44 🐛 fix(git): Add `docs/**` branch
  .github/labeler.yml
Labels: type/fix, scope/git, size/xs, usr/wanjohi

#42 📝 docs: Add README.md
  .github/labeler.yml
  README.md
  assets/banner.png
  assets/logo-name-black.png
  assets/logo-name-white.png
  assets/logo.png
  assets/star-us.png
Labels: scope/git, size/m, usr/wanjohi

#46 🐛 fix(git): Release `warp*` docker images too
  .github/workflows/base.yml
  .github/workflows/warp-input.yml
  .github/workflows/warp.yml
Labels: type/fix, scope/git, size/m, usr/wanjohi

#56 🐛 fix(input): Append `input` to server's session ID for now
  bin/input/src/main.rs
Labels: type/fix, size/xs, usr/wanjohi

#57 🐛 fix(git): Build warp-input on push to main
  .github/workflows/warp-input.yml
Labels: type/fix, scope/git, size/xs, usr/wanjohi

#61 ✨ feat(server): Rename `/netris/proton` to `netris-proton`
  .scripts/entrypoint.sh
  server.Dockerfile
Labels: type/feat, scope/back-end, size/xs, usr/wanjohi

#62 🐛 fix(server): Support the `Open Kernel Module`
  .scripts/entrypoint.sh
Labels: type/fix, size/xs, usr/wanjohi

#63 ✨ feat(server): Add startup script
  .scripts/startup.sh
  .scripts/supervisord.conf
  .scripts/supervisord.d/game.ini
  dev/build.sh
  dev/run-input.sh
  dev/run.sh
  dev/script.sh
  server.Dockerfile
Labels: type/feat, scope/back-end, size/s, size/m, usr/wanjohi

#64 ✨ feat(server): Add warp-input server
  .scripts/supervisord.conf
  server.Dockerfile
Labels: type/feat, scope/back-end, size/s, usr/wanjohi

#65 🐛 fix(input): Retry when namespace doesn't exist
  bin/input/Cargo.toml
  bin/input/src/cli.rs
  bin/input/src/input.rs
  bin/input/src/main.rs
Labels: type/fix, size/m, usr/wanjohi

#66 🐛 fix(server): Final touches
  .scripts/entrypoint.sh
  .scripts/proton
  .scripts/supervisord.conf
  server.Dockerfile
Labels: type/fix, scope/back-end, size/xl, usr/wanjohi

#69 📝 docs(readme): Add manual setup and game launch instructions
  README.md
Labels: size/s, size/m, usr/wanjohi

#73 🐛 fix(server): Remove `xargs` from startup.sh
  .scripts/startup.sh
Labels: type/fix, reg/docker
